version: '3.8'

services:
  app:
    image: thaily/musicbe
    container_name: musicbe
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env