version: '3.8'

services:
  app:
    image: thaily/musicbe
    container_name: musicbe
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    env_file:
      - .env